# Generated by Django 5.2.8 on 2025-11-13 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('es_miembro', models.BooleanField(default=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vecino',
                'verbose_name_plural': 'Vecinos',
            },
        ),
        migrations.CreateModel(
            name='ProyectoVecinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_postulacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.vecino')),
            ],
            options={
                'verbose_name': 'Proyecto Vecinal',
                'verbose_name_plural': 'Proyectos Vecinales',
            },
        ),
        migrations.CreateModel(
            name='CertificadoResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('codigo_certificado', models.CharField(blank=True, max_length=50)),
                ('pdf_generado', models.BooleanField(default=False)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.vecino')),
            ],
            options={
                'verbose_name': 'Certificado de Residencia',
                'verbose_name_plural': 'Certificados de Residencia',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('cupos', models.IntegerField()),
                ('inscritos', models.ManyToManyField(blank=True, related_name='actividades', to='gestion.vecino')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
