# Generated by Django 5.2.8 on 2025-11-14 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_vecino_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioComunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('cancha', 'Cancha'), ('sala', 'Sala'), ('plaza', 'Plaza')], max_length=20)),
                ('descripcion', models.TextField()),
                ('capacidad', models.IntegerField(help_text='Capacidad máxima de personas')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Espacio Comunitario',
                'verbose_name_plural': 'Espacios Comunitarios',
            },
        ),
        migrations.CreateModel(
            name='ReservaEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.CharField(choices=[('manana', 'Mañana (08:00 - 13:00)'), ('tarde', 'Tarde (13:00 - 18:00)'), ('noche', 'Noche (18:00 - 22:00)'), ('dia_completo', 'Día Completo (08:00 - 22:00)')], max_length=20)),
                ('motivo', models.TextField(help_text='Motivo de la reserva')),
                ('cantidad_personas', models.IntegerField(help_text='Cantidad estimada de personas')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('observaciones_admin', models.TextField(blank=True, help_text='Observaciones del administrador')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion.espaciocomunitario')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion.vecino')),
            ],
            options={
                'verbose_name': 'Reserva de Espacio',
                'verbose_name_plural': 'Reservas de Espacios',
                'ordering': ['-fecha_solicitud'],
                'unique_together': {('espacio', 'fecha', 'horario', 'estado')},
            },
        ),
    ]
