# Generated by Django 5.0.9 on 2025-11-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_reservaespacio_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
        migrations.AddField(
            model_name='vecino',
            name='comuna',
            field=models.CharField(default='', max_length=100),
        ),
    ]
